version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile-prod
    ports:
      - "80:80"
    environment:
      # - APP_DEBUG=false
      - DB_CONNECTION=mysql # pgsql
      - DB_HOST=mysql.example.com
      - DB_PORT=3306 # 5432
      - DB_DATABASE=exampledb
      - DB_USERNAME=exampleuser
      - DB_PASSWORD=examplepassword
      # - MAIL_HOST=smtp.example.com
      # - MAIL_PORT=587
      # - MAIL_USERNAME=
      # - MAIL_PASSWORD=
      # - MAIL_ENCRYPTION=tls
      # - MAIL_FROM_ADDRESS=mail@exampe.com
      # - MAIL_FROM_NAME="Free Shop"
      # - TWILIO_ACCOUNT_SID=
      # - TWILIO_AUTH_TOKEN=
      # - TWILIO_FROM=
      # - TWILIO_SMS_SERVICE_SID=
      # - GOOGLE_CLIENT_ID=
      # - GOOGLE_CLIENT_SECRET=
      # - GOOGLE_REDIRECT_URI=http://example.com/backend/login/google/callback
      # - GOOGLE_ORGANIZATION_DOMAIN=
    # volumes:
    #   - logs:/var/www/html/storage/logs
    #   - appdata:/var/www/html/storage/app
# volumes:
#   logs:
#   appdata:
