name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PHP_BIN: php81
  PHP_VERSION: "8.1"
  NODE_VERSION: "16"

jobs:
  laravel-tests:
    name: Laravel tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --no-progress
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install packages via NPM
        run: npm ci
      - name: Audit NPM packages
        run: npm audit --omit dev
      - name: Build assets
        run: npm run build
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
          CACHE_DRIVER: array
          SESSION_DRIVER: array
          QUEUE_DRIVER: sync
        run: vendor/bin/phpunit

  deploy-to-staging:
    name: Deploy to staging
    environment: staging
    runs-on: ubuntu-latest
    needs: [laravel-tests]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
      - name: Log git hash
        shell: bash
        run: |
          echo "Commit: $(git rev-parse --short HEAD)" >> .gitinfo
          echo "Branch: ${GITHUB_REF#refs/heads/}" >> .gitinfo
          echo "Build date: $(date)" >> .gitinfo
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist  --optimize-autoloader --no-dev
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: npm run build
      - name: Enable maintenance mode on remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.REMOTE_TARGET }}
            if [ -f .env ] && [ -f artisan ]; then ${{ env.PHP_BIN }} artisan down; fi
      - name: Deploy to remote
        uses: easingthemes/ssh-deploy@v3.0.1
        env:
          ARGS: "-rltgoDzvO --delete --exclude '.env' --exclude '.git' --exclude 'storage/app/' --exclude 'storage/framework/' --exclude 'storage/logs/' --exclude 'node_modules' --exclude '.vscode' --exclude '.github'"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
      - name: Publish on remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.REMOTE_TARGET }}
            mkdir -p storage/framework/{sessions,views,cache}
            ${{ env.PHP_BIN }} artisan optimize
            ${{ env.PHP_BIN }} artisan view:clear
            ${{ env.PHP_BIN }} artisan migrate --force
            ${{ env.PHP_BIN }} artisan storage:link
            ${{ env.PHP_BIN }} artisan up
